apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatekeeper-controller-manager
  namespace: gatekeeper-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatekeeper-controller-manager
  template:
    metadata:
      labels:
        app: gatekeeper-controller-manager
    spec:
      serviceAccountName: gatekeeper-admin
      containers:
        - name: manager
          image: ghcr.io/open-policy-agent/gatekeeper:v3.9.2
          command:
            - /manager
          args:
            - --metrics-addr=0.0.0.0:8080
          ports:
            - containerPort: 8443
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gatekeeper-controller-manager
  namespace: gatekeeper-system
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: gatekeeper-controller-manager

