apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mazherarsh/ArgoCD/tree/main/manifests/my-opa-configs'
    targetRevision: HEAD
    path: manifests/opa-gatekeeper
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
